import './globals.css'
import { Inter } from 'next/font/google'
import AuthContext from './components/AuthContext'
import Providers from './GlobalRedux/Provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Netflix',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <AuthContext>
      <Providers>
      <html lang="en">
      <body className={inter.className}>
          {children}
        </body>
    </html>
      </Providers>
    
    </AuthContext>
  )
}
